### ISSUE TITLE
Adding custom datasets.

### ISSUE THREAD

**Issue by vkrishnamurthy11** [JieyuZ2/wrench#1]
How can I go about adding my own datasets to the wrench framework so that I can perform experiments?

Thanks!

**Comment by JieyuZ2** [comment]
Hi, 

Thank you for your interest! We will soon add a new wiki page about dataset formatting and usage.

**Comment by JieyuZ2** [comment]
here it is: https://github.com/JieyuZ2/wrench/wiki/Dataset:-Format-and-Usage

Also, it would be great if you could donate your own dataset to wrench and make the community better!
