### ISSUE TITLE
Clarifying dataset download links

### ISSUE THREAD

**Issue by jason-fries** [JieyuZ2/wrench#16]
Great work on the benchmark! 

Under the "Available Datasets" section on the main README, you provide 2 links for downloading the WRENCH datasets:
- [Google drive folder](https://drive.google.com/drive/folders/1v55IKG2JN9fMtKJWU48B_5_DcPWGnpTq?usp=sharing)
- Zip file download [datasets.zip](https://drive.google.com/uc?id=19wMFmpoo_0ORhBzB6n16B1nRRX508AnJ)

One point of confusion is that expanded datasets found on the Google drive link are different than the direct download zip file. For example, `classification/youtube/train.json` on Google drive has 1686 instances while the zip file contains 1586 for the same file, matching the statistics reported on the README. Can you make the correct file download unambiguous in the documentation?

**Comment by JieyuZ2** [comment]
Hey Jason,

Sorry for the point of confusion! The train data with more examples indeed includes the "dev" set and the idx of the "dev" set can be found in the `labeled_ids.json` file. I will update the documentation ASAP. Thanks!

**Comment by jason-fries** [comment]
Awesome -- thank you @JieyuZ2 !!
