### ISSUE TITLE
Reproducing Table 11 for classification

### ISSUE THREAD

**Issue by pmangg** [JieyuZ2/wrench#23]
Thanks for this package @JieyuZ2 -- do you happen to have an orchestration script for reproducing Table 11 (and therefore Table 3) in the [Wrench paper](https://arxiv.org/abs/2109.11377)?

**Comment by JieyuZ2** [comment]
Hey @pmangg 

We basically use scripts like [this](https://github.com/JieyuZ2/wrench/blob/main/examples/grid_search.py) for experiments. Hope that will help!

**Comment by mrbeann** [comment]
Hi, @JieyuZ2 . I got a similar problem, and I've tried the search script, but it seems it is still hard to get a fair comparison (meanwhile only part of search spaces are included in the script). Is it possible to offer detailed parameters?

**Comment by JieyuZ2** [comment]
Hey @mrbeann, please see Table 10 of our [paper](https://arxiv.org/pdf/2109.11377.pdf)
