### ISSUE TITLE
Python Package Installation Fails

### ISSUE THREAD

**Issue by bradleyfowler123** [JieyuZ2/wrench#24]
Installing `ws-benchmark` python package fails due to dependency conflict (see stack trace below).

Tested on system:
  - OS: ubuntu
  - Python: 3.8.13
  - Clean VE

Command to replicate:
  - `pip install ws-benchmark`

Stack Trace:
```
ERROR: Cannot install ws-benchmark and ws-benchmark==1.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    ws-benchmark 1.1.1 depends on networkx==2.7
    snorkel 0.9.7 depends on networkx<2.4 and >=2.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by yinxiangshi** [comment]
Hello! Thanks for your report, this is because Snorkel requires a lower version of pkg networkx, we will fix it later today!
As the issue is fixed, we will inform you in this ticket asap.

**Comment by bradleyfowler123** [comment]
Wonderful, thank you!

**Comment by yinxiangshi** [comment]
Hi, Bradley. We have fixed the issue. Sorry for the inconvenience. Thanks for your support. 
If you still have problems, feel free to contact us!

**Comment by bradleyfowler123** [comment]
Just verified, it's now working! - #25
