### ISSUE TITLE
ModuleNotFoundError: No module named 'tokenizations'

### ISSUE THREAD

**Issue by Gnaiqing** [JieyuZ2/wrench#28]
Hi, I faced some problems when trying to install the library. I tried to use `pip install ws-benchmark==1.1.2rc0` as suggested in the document, the installation was successful but when I run the code I faced the error `ModuleNotFoundError: No module named 'tokenizations'`. Then I tried to clone the repository and create the environment using `conda env create -f environment.yml`, but the installation failed due to the following error `FileNotFoundError: [Errno 2] No such file or directory: '/home/naiqing/miniconda3/envs/wrench/lib/python3.6/site-packages/huggingface_hub-0.0.16-py3.8.egg'`. Do you have ideas on what might cause the problem and how can I fix it?

**Comment by yinxiangshi** [comment]
Thanks for your feedback, we will fix this issue ASAP! I will message u when the installation fixed.

**Comment by yinxiangshi** [comment]
If you want to use it right now, just run pip install in the docs and then run `pip install pytokenizations`

**Comment by Gnaiqing** [comment]
Thanks for your suggestion. `pip install pytokenizations` solves the mentioned problem, but there are other problems when I run the tutorials like `ModuleNotFoundError: No module named 'wrench.logging'` and `TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'`. I think it is likely because the code structure has been changed since you design the tutorials. Do you have a previous stable release that is compatible with the tutorials, which I can use before you launch a new stable release?

**Comment by yinxiangshi** [comment]
I am so sorry about that, we forgot to update the tutor. I suggest you use the last stable release version. The full code could be downloaded here: https://github.com/JieyuZ2/wrench/releases/tag/v1.1
And follow the wiki to modify your env: https://github.com/JieyuZ2/wrench/wiki/Environment-Installation
We will release the newest stable version ASAP. Sorry again for that! Thanks for your support!

**Comment by Gnaiqing** [comment]
Thanks for your help! As an update, I tried manual installation following the guide but faced error `ERROR: Package 'huggingface-hub' requires a different Python: 3.6.15 not in '>=3.7.0'` when running `pip install sentence-transformers==1.1.1`, then I tried python3.7 and it works. Will let you know if I face other problems. Thanks for your great work!

**Comment by yinxiangshi** [comment]
@Gnaiqing Plz tell us if u face more problems, it will help us release a stable version! We will notify u when the stable version is released!

**Comment by Gnaiqing** [comment]
Sure, thank you!

**Comment by Gnaiqing** [comment]
@yinxiangshi when I use wrench sometimes I want to inspect specific data item, but current dataset class seems not to support it. Would you consider to add a `__getitem__` method in the new release?

**Comment by yinxiangshi** [comment]
Good idea, can you describe your needed feature more specifically?

**Comment by Gnaiqing** [comment]
Sorry for my late reply. I spend some time reading the code and think about my requirements. I find that you have implemented `__getitem__` for torchdataset classes, but when I run some third party tools there are some incompatibility, because wrench returns a dict for each item, while the third party tool anticipate a tuple of (feature, label). Still I'm not sure if wrench itself needs some modification. It may be helpful if wrench can also returns a tuple of (feature,label) as an optional choice.

**Comment by JieyuZ2** [comment]
Hey @Gnaiqing 

In that case, I think the best practice is to implement a new dataset class since it sounds like a general torch dataset class.

**Comment by Gnaiqing** [comment]
@JieyuZ2 Thanks for your suggestion. I will try this.
