### ISSUE TITLE
Wrong Data Statistics of the SemEval Dataset?

### ISSUE THREAD

**Issue by davidpig** [JieyuZ2/wrench#35]
Dear authors,

thanks a lot for the nice repo!

I noticed that both the WRENCH paper and this repo report the following data statistics on the SemEval dataset:
number of samples in train/validation/test： 1749/200/692

However, I found the data in the link you provided (Google Drive) have 1749, **178**, and **600** samples for training, validation, and test. Maybe I misunderstood something?

Looking forward to hearing from you.

**Comment by JieyuZ2** [comment]
Hey, 

Thanks for pointing this out- it should be a typo and just fixed the table in readme
