### ISSUE TITLE
datasets.zip in google drive is not updated

### ISSUE THREAD

**Issue by liamtoran** [JieyuZ2/wrench#46]
Hi,

First of all thank you for the awesome benchmark.

In the google drive datasets, it seems the datasets.zip is not updated. It dates from prior to the last update of the datasets /  classification folders, and is missing the train.json in the commercial dataset for instance.

I think it would be advisable to delete this archive as its possible to download the above directly from google drive, or update it.

Thank you

**Comment by JieyuZ2** [comment]
You are right, thank you for pointing this out. Already remove the zip file.
