### ISSUE TITLE
Is there a limitation of using dataset for different algs?

### ISSUE THREAD

**Issue by mrbeann** [JieyuZ2/wrench#5]
Firstly, thank you for building this awesome benchmark. While I try the example with different datasets (e.g., I try astra with youtube dataset), I got some errors like this,
```
    loss = cross_entropy_with_probs(predict_l, batch['labels'].to(device))
KeyError: 'labels'
```
Can this be fixed?

**Comment by JieyuZ2** [comment]
Hey did you use the new youtube dataset in the classification folder in this [link](https://drive.google.com/drive/folders/1v55IKG2JN9fMtKJWU48B_5_DcPWGnpTq?usp=sharing)?

The youtube dataset is updated, but the dataset.zip hasn't.  I could run astra with youtube dataset

**Comment by JieyuZ2** [comment]
Oh did you use Bert backbone?

**Comment by mrbeann** [comment]
Yeah, I use BERT. And I just pull the newest version. It seems some errors are fixed but it still raises errors.
```
    weak_labels = batch['weak_labels'].long().to(device)
KeyError: 'weak_labels'
```

**Comment by JieyuZ2** [comment]
@mrbeann sry, one minute!

**Comment by mrbeann** [comment]
Thanks for the quick fix, it works. And, it will be great if this repo can include some benchmark results of different algorithms.
