### ISSUE TITLE
Using Multiple GPUs

### ISSUE THREAD

**Issue by tolgayan** [JieyuZ2/wrench#7]
Hi,

Is it possible to use multiple GPUs for the experiments, or will it be in future releases? It would be a nice feature if it is not possible right now. 

Best regards.

**Comment by JieyuZ2** [comment]
Hey @tolgayan, yeah we're definitely planning this feature! But may need several weeks

**Comment by tolgayan** [comment]
Okay, thank you for your elegant nice work.

**Comment by JieyuZ2** [comment]
hey @tolgayan check this [example](https://github.com/JieyuZ2/wrench/blob/main/examples/run_torch_ddp.py) out! But haven't got time to do a rigorous test.

**Comment by tolgayan** [comment]
It is impressive how fast you are. Thanks a lot!
