### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by rsmith49** [JieyuZ2/wrench#8]
Hi! Love the repo, super useful so far and really easy interface to use. Thanks for putting it together!

I was wondering if there were plans to cut another release any time soon? We use the `v1.0` tag for making sure the version is consistent across multiple builds. Noticed a few bug fixes and QOL improvements since the last release, and those would be nice to have marked at a new tag.

**Comment by JieyuZ2** [comment]
sure! just published a new release

**Comment by rsmith49** [comment]
Thanks!
