### ISSUE TITLE
Releasing labeling functions?

### ISSUE THREAD

**Issue by dsam99** [JieyuZ2/wrench#9]
Hi, thanks for putting this benchmark together! Would it be possible to also release the labeling functions for the datasets (rather than just the vote matrices)?

**Comment by JieyuZ2** [comment]
hey @dsam99 as the LFs were created by previous work, we included the description and links to the original repo in the readme of each data folder. You could find the LFs in their original repo if they release, otherwise, we only have vote matrices.

Thanks!
